version: '3'
services:
  web:
    restart: on-failure
    container_name: "go-repository"
    build: ./
    command: ./main
    volumes:
      - "./public:/app/public"
    ports:
      - "8080:8080"
    environment:
      DB_DRIVER: ${DB_DRIVER}  
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
    env_file:
      - .env  
    depends_on:
      - db
      #  condition: service_healthy

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env  
    ports:
      - "5432:5432" 
    # healthcheck:
    #  test: ["CMD", "sh", "-c", "/app/healthcheck.sh"]  
    #  interval: 10s
    #  timeout: 5s
    #  retries: 3

  migrator:
    image: migrate/migrate
    volumes:
      - ./internal/infrastructure/db/migrate/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable",
      ] 
    command: ["up"]        
    depends_on:
      - db
    restart: on-failure  